name: build_osmium

on:
  push:

jobs:

  build_tiles_osmium:
    runs-on: ubuntu-latest
    container:
      image: zhibek/osm-toolbox:1.1.0
      env:
        DOCKER: false
        AREA: asia
      volumes:
        - .:/workspace
      options: --workdir /workspace
    steps:
    - uses: actions/checkout@v3
    - run: bash scripts/build-osmium.sh
    - run: ls -lah data
    # TODO: Upload tiles to gh-pages
