name: main

on:
  push:

jobs:

  build_tiles_osmium:
    runs-on: ubuntu-latest
    container:
      image: zhibek/osm-toolbox:1.1.0
      env:
        DOCKER: false
        AREA: andorra
      volumes:
        - .:/workspace
      options: --workdir /workspace
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p data/source; mkdir -p data/tmp; bash scripts/build-osmium.sh

  build_tiles_plantiler:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/onthegomap/planetiler:0.6-SNAPSHOT
      env:
        DOCKER: false
        AREA: andorra
    steps:
    - uses: actions/checkout@v2
    - run: java -jar run.jar generate-custom --download --schema=config/railways.yml --area="$AREA" --output="data/$AREA.planetiler.mbtiles"
