name: main

on:
  push:

jobs:

  build_tiles_osmium:
    runs-on: ubuntu-latest
    container:
      image: zhibek/osm-toolbox:1.1.0
      env:
        DOCKER: false
        AREA: andorra
      volumes:
        - .:/workspace
      options: --workdir /workspace
    steps:
    - uses: actions/checkout@v3
    - run: ls -lah data
    - run: bash scripts/build-osmium.sh
    - run: ls -lah data

  build_tiles_plantiler:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/onthegomap/planetiler:0.6-SNAPSHOT
      env:
        DOCKER: false
        AREA: andorra
    steps:
    - uses: actions/checkout@v3
    - run: ls -lah data
    - run: bash scripts/build-planetiler.sh
    - run: ls -lah data
